[package]
name = "graphql_client"
version = "0.9.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]
description = "Typed GraphQL requests and responses"
repository = "https://github.com/graphql-rust/graphql-client"
license = "Apache-2.0 OR MIT"
keywords = ["graphql",  "api", "web", "webassembly", "wasm"]
categories = ["network-programming", "web-programming", "wasm"]
edition = "2018"

[dependencies]
doc-comment = "^0.3"
anyhow = { version = "1.0", optional = true }
thiserror = { version = "1.0", optional = true }
graphql_query_derive = { path = "../graphql_query_derive", version = "0.9.0" }
serde_json = "1.0"
serde = { version = "^1.0.78", features = ["derive"] }
reqwest = { version = "0.10", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
reqwest = "^0.10"

[features]
web = ["reqwest"]
